excluded:
  - Pods
  - fastlane
  - vendor

force_cast: warning

opt_in_rules:
  - multiline_literal_brackets
  - multiline_parameters
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - yoda_condition

line_length: 120
identifier_name:
  min_length: 1
  max_length: 50
function_body_length:
  error: 200
