osx_image: xcode11.2
language: swift
xcode-project: Headlines.xcodeproj
xcode_scheme: Headlines
xcode_sdk: iphonesimulator13.2

before_install:
  - bundle install

script:
  - fastlane test
  - bundle exec danger
