osx_image: xcode11.2
language: swift
xcode-project: Headlines.xcworkspace
xcode_scheme: Headlines
xcode_sdk: iphonesimulator13.2

before_install:
  - bundle install
  - pod repo update

script:
  - fastlane test
  - bundle exec danger
