osx_image: xcode8.3
language: objective-c
xcode-project: Headlines.xcworkspace
xcode_scheme: Headlines
xcode_sdk: iphonesimulator10.0

script:
  - set -o pipefail
  - xcodebuild -workspace Headlines.xcworkspace -scheme Headlines -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - bundle exec danger
