osx_image: xcode10.2
language: swift
xcode-project: Headlines.xcworkspace
xcode_scheme: Headlines
xcode_sdk: iphonesimulator12

before_install:
  - pod repo update

script:
  - fastlane test
  - bundle exec danger
