osx_image: xcode11
language: swift
xcode-project: Headlines.xcworkspace
xcode_scheme: Headlines
xcode_sdk: iphonesimulator13.0

before_install:
  - bundle install

script:
  - fastlane test
  - bundle exec danger
