osx_image: xcode9.4
language: objective-c
xcode-project: Headlines.xcworkspace
xcode_scheme: Headlines
xcode_sdk: iphonesimulator10.3

before_install:
  - pod repo update

script:
  - fastlane test
  - bundle exec danger
