# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.8"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "HeadlinesUITests")
  end

  lane :has_fabric_tokens do
    api_key = sh "cat ../fabric.apikey"
    build_secret = sh "cat ../fabric.buildsecret"
    !api_key.to_s.empty? && !build_secret.to_s.empty?
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    unless has_fabric_tokens
      UI.user_error!("ERROR: Your fabric tokens are empty. You won't track anything.")
    end

    increment_build_number(
      build_number: latest_testflight_build_number + 1,
    )

    gym(scheme: "Headlines") # Build your app - more options available

    pilot(
      skip_waiting_for_build_processing: true,
      beta_app_feedback_email: "ezequiel@betzerra.com.ar"
    )

    # crashlytics
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Headlines") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
