# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.120"

default_platform :ios

ENV["FASTLANE_ITC_TEAM_NAME"] = "Ezequiel Alejandro Becerra"

platform :ios do

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Headlines")
  end

  private_lane :get_build_number_from_plist do
    #This is required because default action "get_build_number" is bugged
    %x[/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "../PatientApp/PatientAppEnterprise-Info.plist"].strip
  end

  private_lane :get_version_from_plist do
    %x[/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "../PatientApp/PatientAppEnterprise-Info.plist"].strip
  end

  private_lane :get_tag do
    "#{get_version_from_plist}.#{get_build_number_from_plist}"
  end

  lane :version_bump do
    version_from_git = sh "git rev-list HEAD --count"
    version_from_plist = get_build_number_from_plist

    if version_from_git != version_from_plist
      new_version = version_from_git.to_i + 1
      increment_build_number(
        build_number: new_version
      )
    end
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    version_bump
    commit_version_bump(
      force: true
    )

    gym(
      scheme: "Headlines",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    ) # Build your app - more options available

    pilot(
      skip_waiting_for_build_processing: true,
      beta_app_feedback_email: "ezequiel@betzerra.com.ar"
    )

    # crashlytics
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Headlines") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
