# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPad Pro (10.5-inch)",
  "iPad Pro (12.9-inch)",
  "iPhone X"
])

languages([
  "es-ES",
])

# The name of the scheme which contains the UI Tests
scheme "SnapshotUITests"

ios_version '12.0'

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
workspace "./Headlines.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
